"""empty message

Revision ID: 179402c9e929
Revises: 100ca7abebc0
Create Date: 2024-12-17 08:59:40.840275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179402c9e929'
down_revision = '100ca7abebc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_accounts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('sub_accounts')

    # ### end Alembic commands ###
