"""empty message

Revision ID: 1ddc2557c76f
Revises: 6dc1914262a6
Create Date: 2024-12-31 07:11:51.927902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddc2557c76f'
down_revision = '6dc1914262a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tithe_pledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_pledged', sa.Float(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tithe_pledge')
    # ### end Alembic commands ###
