"""empty message

Revision ID: 73111810ebc1
Revises: 179402c9e929
Create Date: 2024-12-17 09:34:29.359038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73111810ebc1'
down_revision = '179402c9e929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_accounts', sa.JSON(), nullable=True))

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_accounts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('sub_accounts')

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.drop_column('sub_accounts')

    # ### end Alembic commands ###
